# Generated by Django 3.0.5 on 2020-08-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='last name'),
        ),
    ]
